apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static-deployment
  namespace: web-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-static
  template:
    metadata:
      labels:
        app: web-static
    spec:
      containers:
        - name: web-server
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
