apiVersion: v1
kind: Service
metadata:
  name: web-static-service
  namespace: web-static
spec:
  type: NodePort
  selector:
    app: web-static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Puerto que abriremos en el nodo
